---
abstract: 'Data representation as a table, including file IO.'
author:
  - 'Stuart R. Jefferys <srjefferys (at) gmail (dot) com>'
build_requires:
  Test::MockModule: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-SeqWare-File-Table
provides:
  Bio::SeqWare::File::Table:
    file: lib/Bio/SeqWare/File/Table.pm
    version: 0.000002
requires:
  perl: 5.014
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.000002
